version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/supplements-shop
      - JWT_SECRET=test123
      - PAYPAL_CLIENT_ID=AVCQQo3yTpvgVcw5r0eMjUBR3SkL2c1tVOLKPELQmrZTsAi1CvviLbJNiHFxGQWfXT1-YRJepswuFnJR
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
