version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    volumes:
      - ./backend:/app/backend
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
